services:
  - type: worker
    name: scheduling-bot
    env: python
    plan: starter
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromDotEnv: true
